# Generated by Django 5.1.2 on 2025-01-27 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hand', models.JSONField(default=list)),
                ('played_words', models.JSONField(default=list)),
                ('last_played_time', models.DateTimeField(blank=True, null=True)),
                ('cooldown_remaining', models.IntegerField(default=0)),
                ('placed_tiles', models.JSONField(blank=True, default=list)),
                ('placed_tiles_history', models.JSONField(blank=True, default=list)),
                ('zoom', models.IntegerField(default=12)),
                ('lastx', models.IntegerField(default=0)),
                ('lasty', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('is_blank', models.BooleanField(default=False)),
                ('effects', models.JSONField(blank=True, null=True)),
                ('mode', models.CharField(max_length=16)),
                ('points', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BoardTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.tile')),
            ],
        ),
    ]
