# Generated by Django 5.1.2 on 2024-11-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardtile',
            old_name='x_coordinate',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='boardtile',
            old_name='y_coordinate',
            new_name='y',
        ),
        migrations.AlterUniqueTogether(
            name='boardtile',
            unique_together={('x', 'y')},
        ),
    ]
