# Generated by Django 5.1.2 on 2024-11-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_x_coordinate_boardtile_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='mode',
            field=models.CharField(default='filled', max_length=16),
            preserve_default=False,
        ),
    ]
