# Generated by Django 5.1.2 on 2024-11-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_tile_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='owner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
