# Generated by Django 5.1.2 on 2024-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_tile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='current_hand',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='played_words',
            field=models.JSONField(default=list),
        ),
    ]
