# Generated by Django 5.1.2 on 2024-11-03 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_tile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile'),
        ),
    ]
