# Generated by Django 5.1.2 on 2024-11-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_tile_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardtile',
            unique_together=set(),
        ),
    ]
