# Generated by Django 5.1.2 on 2024-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_boardtile_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='zoom',
            field=models.IntegerField(default=12),
        ),
    ]
