# Generated by Django 5.1.2 on 2024-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_playerprofile_zoom'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
