# Generated by Django 5.1.2 on 2024-11-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_tile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='lastx',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='lasty',
            field=models.IntegerField(default=0),
        ),
    ]
