# Generated by Django 5.1.2 on 2024-11-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_playerprofile_lastx_playerprofile_lasty'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
