# Generated by Django 5.1.2 on 2024-11-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_playerprofile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='word_count',
            field=models.IntegerField(default=0),
        ),
    ]
